[versions]
kotlin = "1.9.21"
compose = "1.5.12"

[plugins]
compose = {id = "org.jetbrains.compose", version.ref = "compose"}
multiplatform = {id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin"}
